issue #39 Update package dependencies version resolved
ruxailab/web-eye-tracker-front pull request #44
Opened 2024-03-24 20:36 UTC by Raju-Mannem

now the app is running on nodejs version 20x which has Long Term Support till 2026 
In this commit most of the deprecated packages were updated to latest versions and some were removed.
Some configuration changes were made.

2024-04-24 18:04 UTC, JulioManoel requested changes
Two errors were identified:
- Multiple clicks on login button with Google
- When you go to the /record screen and return to the previous screen

2024-04-25 15:49 UTC, Raju-Mannem commented
Hai @JulioManoel 

I was checking with the code.
could you please attach screenshots or clips?
This way can help to dive deeper.

2025-01-29 10:22 UTC, marcgc21 commented on src/services/auth.js
@Raju-Mannem can you explain me why it is using this /compat? It has updated the way that firebase is imported?

2025-03-10 14:15 UTC, marcgc21 commented
Closed due to inactivity.

2025-03-10 14:15 UTC, closed without merging